import { EnvModel } from '../model/env.model'

/**
 * Env config
 */
export default (): EnvModel => ({
  OPEN_AI_PORT: parseInt(process.env.OPEN_AI_PORT, 10) || 3000,
  OPEN_AI_APP_NAME: process.env.OPEN_AI_APP_NAME,
  OPEN_AI_FIREBASE_API_KEY: process.env.OPEN_AI_FIREBASE_API_KEY,
  OPEN_AI_FIREBASE_AUTH_DOMAIN: process.env.OPEN_AI_FIREBASE_AUTH_DOMAIN,
  OPEN_AI_FIREBASE_PROJECT_ID: process.env.OPEN_AI_FIREBASE_PROJECT_ID,
  OPEN_AI_FIREBASE_STORAGE_BUCKET: process.env.OPEN_AI_FIREBASE_STORAGE_BUCKET,
  OPEN_AI_FIREBASE_MESSAGING_SENDER_ID: process.env.OPEN_AI_FIREBASE_MESSAGING_SENDER_ID,
  OPEN_AI_FIREBASE_APP_ID: process.env.OPEN_AI_FIREBASE_APP_ID,
  OPEN_AI_FIREBASE_MEASUREMENT_ID: process.env.OPEN_AI_FIREBASE_MEASUREMENT_ID,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY
})
